"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
# A minimal left prompt
format = """$directory$git_branch$git_status$conda$character"""
palette = "catppuccin_mocha"
# move the rest of the prompt to the right
right_format = """$all"""

[character]
success_symbol = '[➜](bold fg:sky bg:base)[](bold base)'
error_symbol = '[✖](bold fg:red bg:base)[](bold base)'

[directory]
style = 'bold fg:blue bg:base'
format = '[](bold base)[$path ]($style)[$read_only]($read_only_style)'
read_only_style = 'bold fg:red bg:mantle'
truncation_length = 5
truncation_symbol = '…/'
truncate_to_repo = true

[golang]
format = '[ ](bold cyan)'

[git_branch]
format='[$symbol$branch(:$remote_branch) ](bold bg:base fg:maroon)'
style='bold bright fg:white bg:base'
symbol=" "

[git_status]
format = '[\[$all_status$ahead_behind\] ](bold bg:base fg:maroon)'
style = 'bold fg:maroon bg:base'
disabled = ["status_clean"]

# What's with the spacing?
[os]
disabled=true


[package]
disabled=true

[nodejs]
disabled=true

[conda]
format = '[($environment) ](bold fg:green bg:base)'
ignore_base = false
style = 'fg:green bg:base'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
